backend:
  name: github
  repo: binquan1/leo
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "videos"
    label: "视频"
    folder: "videos"
    create: true

    fields:
      - { label: "视频标题", name: "title", widget: "string" }

      - { label: "视频描述", name: "description", widget: "text" }

      - { label: "YouTube嵌入链接", name: "youtube", widget: "string" }

      - { label: "视频分类", name: "category", widget: "string" }
