backend:
  name: github
  repo: binquan1/my-video-site
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "videos"
    label: "视频"
    folder: "videos"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"

    fields:
      - { label: "视频标题", name: "title", widget: "string" }

      - { label: "视频描述", name: "description", widget: "text" }

      - { label: "YouTube嵌入链接", name: "youtube", widget: "string" }

      - label: "视频分类"
        name: "category"
        widget: "select"
        options:
          - "教程"
          - "美食"
          - "游戏"
          - "音乐"
          - "其它"
